apiVersion: v1
kind: Secret
metadata:
  name: cluster02-secret
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: cluster02
  server: https://api.acidonpe34.sandbox766.opentlc.com:6443
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ikx6cG83TzVONGxOQTJQMl95MFpHbzFJWWRfMTl6YVBaWlFSa3VWd29aVkUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFwaW1hbmFnZXIwMS10b2tlbi00Z2s3NyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhcGltYW5hZ2VyMDEiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJhODUxODBmNi0xY2JlLTQ1MjktODk0MS1mZmI4OGFhN2NiZWUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDphcGltYW5hZ2VyMDEifQ.SeX3l5JOrAlh9e4HSm4btUntJ3APBGGhaICbTRV93iQFhh6zUhoCgCR8bCbweJVv4gXm21QT3VttKPW41cbog0PKmmKuck9ILYOwSuwn3FU-_7plcukYqB5FJwCgBi6UzwD92S_BC5PUXVGP5x-MMHRi14LIIpqX4XA1GxU30YUIrxgcSKrWOeZjiH7zwBZ6RVRtDh6nF7dvBpa7xm8nC3L4-vN8T7c7pJO6wSvaoikqD5yBSwBNvHfzAWLd3hSjB5hgmCrni5KzkiTl7v-9Bc-s61Wcfww0D98Nb2-FtC5WkkA8LbFEGECtjuWQcPatWVAKduldlQBGg3WfINLKNBrKKwnC8ir6yOuChdmOXrefXhHioaCi2qduthsQIpYNjoVYtWzWJKsUdElsMhSA6oz51nBP3HB87pDpnEJa5r2Rx85pk7HdnYGXboUlMBYi8dbVMeKdGvwVjfPldJKBy3ugPkcS5zJQc_Plq2XgE5GoHK-OitjyL4qaXgljcWS8HCM5zljRMBPOcfp4f-ZwQe-nJy2u7B3Ogb9kCDLCR8iv9pPOuSi-wk4fyu1OEZUTzzVd80Aw6MkBfRCtf9PtVEg-uoW4507_BIEcNwQ49ijXL6dbieoysAbM9EzRDlJaHEgXJvmH40GPRnpGFFTUmNu0_nlKMtB3P3AQj5HLAKA",
      "tlsClientConfig": {
        "insecure": true
      }
    }