apiVersion: v1
kind: Secret
metadata:
  name: cluster02-secret
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: cluster02
  server: https://api.${API_DOMAIN}:6443
  config: |
    {
      "bearerToken": "${API_TOKEN}",
      "tlsClientConfig": {
        "insecure": true
      }
    }