apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: integration
  namespace: openshift-gitops
spec:
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment
    - group: ''
      kind: Service
    - group: 'route.openshift.io'
      kind: Route
    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - 'https://github.com/acidonper/jump-app-gitops.git'
  syncWindows:
  - kind: deny
    schedule: '0 9 * * *'
    duration: 8h
    applications:
    - 'app03-integration'