apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
  name: app03-integration
spec:
  destination:
    name: ''
    namespace: integration
    server: 'https://api.${API_DOMAIN}:6443'
  source:
    path: .
    repoURL: 'https://github.com/acidonper/jump-app-gitops.git'
    targetRevision: 'feature/jump-app-dev'
    helm:
      valueFiles:
        - values-quay.yaml
  project: integration
  syncPolicy:
    automated:
      prune: false
      selfHeal: false  